language: bash

addons:
  apt:
    update: true

jobs:
  include: 
    - stage: "Compile Check"
      os: windows
      script: ./compile-test.sh
    - stage: "Build Documentation"
      os: linux
      install: sudo ./documentation-install.sh
      script: sudo ./documentation-build.sh
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: false
        local-dir: docgen/build/html
        on:
          branch: master